
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 36, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 11:53:48] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 36, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:00:59] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:01:04] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:01:04] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:–í—ã–ø–æ–ª–Ω—è—é –ø–æ–∏—Å–∫
ERROR:root:–§–∞–π–ª –¥–ª—è –∑–∞–ø–∏—Å–∏ –ø–æ–≤—Ä–µ–∂–¥—ë–Ω
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:01:07] "GET /search/?s=–∫—Ä–∞—Å–∏–≤—ã–π HTTP/1.1" 200 -
INFO:root:–í—ã–ø–æ–ª–Ω—è—é –ø–æ–∏—Å–∫
ERROR:root:–§–∞–π–ª –¥–ª—è –∑–∞–ø–∏—Å–∏ –ø–æ–≤—Ä–µ–∂–¥—ë–Ω
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:02:00] "GET /search/?s=–∫—Ä–∞—Å–∏–≤—ã–π HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:02:03] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:02:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 36, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:02:11] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 37, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:03:06] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:24] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:–í—ã–ø–æ–ª–Ω—è—é –ø–æ–∏—Å–∫
ERROR:root:–§–∞–π–ª –¥–ª—è –∑–∞–ø–∏—Å–∏ –ø–æ–≤—Ä–µ–∂–¥—ë–Ω
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:30] "GET /search/?s=–∫—Ä–∞—Å–∏–≤—ã–π HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:34] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:37] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:39] "GET /post HTTP/1.1" 200 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 37, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:09:44] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:33] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:46] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:46] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:46] "GET /uploads/images/Sophie.jpeg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:49] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:55] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:–í—ã–ø–æ–ª–Ω—è—é –ø–æ–∏—Å–∫
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:59] "GET /search/?s=–°–æ—Ñ–∏ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:59] "[36mGET /uploads/images/Sophie.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:22:59] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:23:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:23:35] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:–í—ã–ø–æ–ª–Ω—è—é –ø–æ–∏—Å–∫
ERROR:root:–§–∞–π–ª –¥–ª—è –∑–∞–ø–∏—Å–∏ –ø–æ–≤—Ä–µ–∂–¥—ë–Ω
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:23:42] "GET /search/?s=–°–æ—Ñ–∏ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:23:47] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:23:47] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kseniia/PycharmProjects/12_HW_/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kseniia/PycharmProjects/12_HW_/loader/views.py", line 38, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 18, in add_post
    posts: list[dict] = load_posts()
  File "/Users/kseniia/PycharmProjects/12_HW_/functions.py", line 6, in load_posts
    return json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2854 (char 2853)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2022 12:24:03] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
